{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4e2dccd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6910060a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 337, in polling_action_cb\n",
      "    updates = self.bot.get_updates(self.last_update_id,\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/decorator.py\", line 232, in fun\n",
      "    return caller(func, *(extras + args), **kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 67, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 2138, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 330, in post\n",
      "    result = self._request_wrapper('POST', url,\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 337, in polling_action_cb\n",
      "    updates = self.bot.get_updates(self.last_update_id,\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/decorator.py\", line 232, in fun\n",
      "    return caller(func, *(extras + args), **kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 67, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 2138, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 330, in post\n",
      "    result = self._request_wrapper('POST', url,\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 337, in polling_action_cb\n",
      "    updates = self.bot.get_updates(self.last_update_id,\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/decorator.py\", line 232, in fun\n",
      "    return caller(func, *(extras + args), **kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 67, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 2138, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 330, in post\n",
      "    result = self._request_wrapper('POST', url,\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 337, in polling_action_cb\n",
      "    updates = self.bot.get_updates(self.last_update_id,\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/decorator.py\", line 232, in fun\n",
      "    return caller(func, *(extras + args), **kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 67, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 2138, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 330, in post\n",
      "    result = self._request_wrapper('POST', url,\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/ext/updater.py\", line 337, in polling_action_cb\n",
      "    updates = self.bot.get_updates(self.last_update_id,\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/decorator.py\", line 232, in fun\n",
      "    return caller(func, *(extras + args), **kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 67, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/bot.py\", line 2138, in get_updates\n",
      "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 330, in post\n",
      "    result = self._request_wrapper('POST', url,\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/huzeyfe/anaconda3/lib/python3.11/site-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from telegram import Update\n",
    "from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackContext\n",
    "\n",
    "# توكن البوت الخاص بك\n",
    "TOKEN = \"6897793371:AAE9aIQm15aDIWuzsPKz5pOY-yK1FzfN19s\"\n",
    "\n",
    "# اسم ملف النص\n",
    "txt_file = 'product_list.txt'\n",
    "\n",
    "# قائمة المنتجات المحظورة الحالية\n",
    "banned_products = []\n",
    "\n",
    "def start(update: Update, context: CallbackContext) -> None:\n",
    "    update.message.reply_text('مرحبًا! أرسل اسم المنتج للتحقق.')\n",
    "\n",
    "def check_product(update: Update, context: CallbackContext) -> None:\n",
    "    user_input = update.message.text\n",
    "\n",
    "    # تحقق مما إذا كان المستخدم أرسل اسم منتج\n",
    "    if not user_input.startswith('/'):\n",
    "        # تحقق من وجود اسماء منتجات محظورة في ملف نصي وأنه غير فارغ\n",
    "        try:\n",
    "            with open(txt_file, 'r') as file:\n",
    "                banned_products = [line.strip().lower() for line in file.readlines()]\n",
    "                print(f\"تم قراءة المنتجات بنجاح: {banned_products}\")\n",
    "\n",
    "        except FileNotFoundError:\n",
    "            print(f\"تحذير: الملف {txt_file} غير موجود.\")\n",
    "        except Exception as e:\n",
    "            print(f\"حدث خطأ أثناء قراءة الملف: {e}\")\n",
    "\n",
    "    # تحقق من ما إذا كان اسم المنتج في قائمة المنتجات المحظورة\n",
    "    if user_input.lower() in banned_products:\n",
    "        update.message.reply_text('وفقاً للبيانات الحالية يجب تجنب استخدام هذا المنتج فهو داعم لإسرائيل وجزاك الله خيراً.')\n",
    "    else:\n",
    "        update.message.reply_text('وفقاً للبيانات الحالية لا يجب مقاطعة هذا المنتج، وبإمكانك استخدامه بحرية. وإذا كان لديك معلومات مغايرة لذلك بإمكانك مراسلتنا ولك جزيل الشكر.')\n",
    "\n",
    "def main() -> None:\n",
    "    updater = Updater(TOKEN, use_context=True)\n",
    "    dp = updater.dispatcher\n",
    "\n",
    "    dp.add_handler(CommandHandler(\"start\", start))\n",
    "    dp.add_handler(MessageHandler(Filters.text & ~Filters.command, check_product))\n",
    "\n",
    "    updater.start_polling()\n",
    "    updater.idle()\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "18a00dcf",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
